//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PS_11_9952_TrabalhoModelo_2021.Admin.Disciplinas
{
    public partial class gerir
    {
    }
}
